baseURL = "http://www.darptolus.com/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "Diego Andres Roa Perdomo"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

[params]
  # LoveIt theme version
  version = "0.2.X"
  # site description
  description = "Diego Andres Roa Perdomo"
  # site keywords
  keywords = ["CAPSL", "HPC"]
  # Home page config
  [params.home]
    # amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "/images/avatar.jpg"
      # title shown in home page (HTML format is supported)
      title = ""
      # subtitle shown in home page
      subtitle = "Electrical & Computer Engineering, Research Assistant"
      # whether to use typeit animation for subtitle
      typeit = false
      # whether to show social links
      social = false
      # disclaimer (HTML format is supported)
      disclaimer = ""



[menu]
  [[menu.main]]
    identifier = "resume"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Resume"
    url = "/resume/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "research"
    pre = ""
    post = ""
    name = "Research"
    url = "/research/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "others"
    pre = ""
    post = ""
    name = "Others"
    url = "/others/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "github"
    pre = "<i class='fab fa-github fa-fw'></i>"
    post = ""
    name = ""
    url = "https://github.com/darptolus"
    title = "GitHub"
    weight = 4

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

#[languages]
#  [languages.en]
#    weight = 1
#    # language code
#    languageCode = "en"
#    # language name
#    languageName = "English"
#    # whether to include Chinese/Japanese/Korean
#    hasCJKLanguage = false
#    # default amount of posts in each pages
#    paginate = 12